---
paths:
  - path: /Users/mdn/works
    section: Visited
  - path: /Users/mdn
    section: Visited
  - path: /Users/mdn/works/rust/workspace/path-genie
    section: Visited
  - path: /Users/mdn/Desktop
    section: Visited
  - path: /Users/mdn/Downloads
    section: Visited
